name: CI/CD Pipeline frontend

on:
  push:
    branches:
      - main

jobs:
  dockerize-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Security Scan
        run: |
          npx eslint . --ext .js,.jsx || true

      - name: Run npm audit for vulnerabilities
        run: npm audit --json > npm-audit-report.json || true

      - name: Upload SAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-sast-reports
          path: |
            ./npm-audit-report.json

      - name: Set up Docker image tag
        id: vars
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-frontend:${{ env.TAG }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-frontend:${{ env.TAG }}
